Repository prgrms-be-devcourse/NBE3-4-2-team05, pull requests merged in 2025-02, with the labels that each got.

#17 [FEAT] : 모임 생성 기능 추가
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassResponse.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassRepository.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
Labels: enhancement

#18 [FEAT] : 소셜 로그인 (카카오) 구현
  backend/README.md
  backend/build.gradle
  backend/src/main/java/z9/second/domain/authentication/controller/AuthenticationController.java
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationService.java
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationServiceImpl.java
  backend/src/main/java/z9/second/domain/kakao/KakaoAuthFeignClient.java
  backend/src/main/java/z9/second/domain/kakao/KakaoResourceFeignClient.java
  backend/src/main/java/z9/second/global/config/FeignClientConfig.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/security/constant/OAuthConstant.java
  backend/src/main/java/z9/second/global/security/oauth/OAuthProperties.java
  backend/src/main/java/z9/second/global/security/oauth/OAuthToken.java
  backend/src/main/java/z9/second/global/security/oauth/user/KakaoUserInfo.java
  backend/src/main/java/z9/second/global/security/oauth/user/OAuth2UserInfo.java
  backend/src/main/java/z9/second/global/security/user/CustomUserDetails.java
  backend/src/main/java/z9/second/model/oauthuser/OAuthProvider.java
  backend/src/main/java/z9/second/model/oauthuser/OAuthUser.java
  backend/src/main/java/z9/second/model/oauthuser/OAuthUserRepository.java
  backend/src/main/java/z9/second/model/user/User.java
  backend/src/main/java/z9/second/model/user/UserStatus.java
  backend/src/main/java/z9/second/model/user/UserType.java
  backend/src/main/resources/config/application-dev_auth.yml
  backend/src/main/resources/config/application-test_auth.yml
  backend/src/main/resources/config/application-test_db.yml
  backend/src/test/resources/config/application-test_auth.yml
Labels: enhancement

#23 [FEAT] : 관심사 조회 기능 구현
  backend/src/main/java/z9/second/domain/favorite/controller/FavoriteController.java
  backend/src/main/java/z9/second/domain/favorite/dto/FavoriteResponse.java
  backend/src/main/java/z9/second/domain/favorite/entity/FavoriteEntity.java
  backend/src/main/java/z9/second/domain/favorite/repository/FavoriteRepository.java
  backend/src/main/java/z9/second/domain/favorite/service/FavoriteService.java
  backend/src/main/java/z9/second/global/initdata/BaseInitData.java
  backend/src/test/java/z9/second/domain/favorite/controller/FavoriteControllerTest.java
  backend/src/test/java/z9/second/integration/SpringBootTestSupporter.java
Labels: enhancement

#25 [FEAT] : Access Token 재발급 절차 구현
  backend/README.md
  backend/build.gradle
  backend/src/main/java/z9/second/domain/authentication/controller/AuthenticationController.java
  backend/src/main/java/z9/second/domain/authentication/dto/AuthenticationResponse.java
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationServiceImpl.java
  backend/src/main/java/z9/second/global/config/RedisConfig.java
  backend/src/main/java/z9/second/global/config/SecurityConfig.java
  backend/src/main/java/z9/second/global/redis/RedisRepository.java
  backend/src/main/java/z9/second/global/response/BaseResponse.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/security/filter/AuthenticationFilter.java
  backend/src/main/java/z9/second/global/security/filter/FilterUtil.java
  backend/src/main/java/z9/second/global/security/filter/ReissueFilter.java
  backend/src/main/java/z9/second/global/utils/ControllerUtils.java
  backend/src/main/resources/config/application-dev_db.yml
  backend/src/test/java/z9/second/domain/authentication/service/AuthenticationServiceImplTest.java
  backend/src/test/java/z9/second/integration/SpringBootTestSupporter.java
  backend/src/test/resources/config/application-test_db.yml
Labels: enhancement

#28 [FEAT] : 회원가입 구현
  backend/src/main/java/z9/second/domain/authentication/controller/AuthenticationController.java
  backend/src/main/java/z9/second/domain/authentication/dto/AuthenticationRequest.java
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationService.java
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationServiceImpl.java
  backend/src/main/java/z9/second/domain/favorite/repository/FavoriteRepository.java
  backend/src/main/java/z9/second/global/annotation/validation/user/UserNickname.java
  backend/src/main/java/z9/second/global/initdata/BaseInitData.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
  backend/src/main/java/z9/second/model/user/UserRepository.java
  backend/src/main/java/z9/second/model/userfavorite/UserFavorite.java
  backend/src/main/java/z9/second/model/userfavorite/UserFavoriteRepository.java
  backend/src/test/java/z9/second/domain/authentication/controller/AuthenticationControllerTest.java
  backend/src/test/java/z9/second/domain/authentication/dto/AuthenticationRequestTest.java
  backend/src/test/java/z9/second/domain/authentication/service/AuthenticationServiceImplTest.java
  backend/src/test/java/z9/second/model/user/UserRepositoryTest.java
Labels: enhancement

#31 [FEAT] : 모임 가입 구현
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassRequest.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassResponse.java
  backend/src/main/java/z9/second/domain/classes/entity/ClassEntity.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassUserRepository.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
Labels: enhancement

#32 [FEAT] : 로그아웃 구현
  backend/src/main/java/z9/second/domain/authentication/controller/AuthenticationController.java
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationService.java
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationServiceImpl.java
  backend/src/main/java/z9/second/global/config/SecurityConfig.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
  backend/src/main/java/z9/second/global/security/filter/AuthenticationFilter.java
  backend/src/main/java/z9/second/global/security/filter/ReissueFilter.java
  backend/src/main/java/z9/second/global/utils/ControllerUtils.java
  backend/src/test/java/z9/second/domain/authentication/controller/AuthenticationControllerTest.java
  backend/src/test/java/z9/second/integration/security/WithCustomUser.java
  backend/src/test/java/z9/second/integration/security/WithCustomUserSecurityContextFactory.java
Labels: enhancement

#27 [FEAT] : 모임방 입장 Controller, Response, Service 생성
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassResponse.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassUserRepository.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
Labels: enhancement

#34 [FEAT] : 모임 탈퇴 기능 구현
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/entity/ClassEntity.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassUserRepository.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
Labels: enhancement

#41 [FEAT] 모임 수정 기능 구현
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassRequest.java
  backend/src/main/java/z9/second/domain/classes/entity/ClassEntity.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
Labels: enhancement

#45 [FIX]: TEST_MEETING_TIME 고정값으로 인한 테스트 실패 해결
  backend/src/test/java/z9/second/domain/schedules/base/SchedulesBaseTest.java
  backend/src/test/java/z9/second/domain/schedules/controller/SchedulesControllerTest.java
  backend/src/test/java/z9/second/domain/schedules/service/SchedulesServiceTest.java
Labels: bug

#47 [FEAT] : 모임 삭제 기능 구현
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassUserRepository.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
Labels: enhancement

#53 [FEAT] : 모임 가입한 회원 강퇴 기능 구현
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/entity/ClassEntity.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
Labels: enhancement

#49 [FEAT] : 회원 정보 조회 및 정보 수정 기능 구현
  backend/src/main/java/z9/second/domain/user/controller/UserController.java
  backend/src/main/java/z9/second/domain/user/dto/UserRequest.java
  backend/src/main/java/z9/second/domain/user/dto/UserResponse.java
  backend/src/main/java/z9/second/domain/user/service/UserService.java
  backend/src/main/java/z9/second/domain/user/service/UserServiceImpl.java
  backend/src/main/java/z9/second/global/config/SecurityConfig.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
  backend/src/main/java/z9/second/model/user/User.java
  backend/src/main/java/z9/second/model/user/UserRole.java
  backend/src/main/java/z9/second/model/user/UserType.java
  backend/src/main/java/z9/second/model/userfavorite/UserFavorite.java
  backend/src/main/java/z9/second/model/userfavorite/UserFavoriteRepository.java
  backend/src/test/java/z9/second/domain/user/controller/UserControllerTest.java
  backend/src/test/java/z9/second/domain/user/dto/UserRequestTest.java
  backend/src/test/java/z9/second/domain/user/service/UserServiceImplTest.java
  backend/src/test/java/z9/second/integration/SpringBootTestSupporter.java
  backend/src/test/java/z9/second/model/userfavorite/UserFavoriteRepositoryTest.java
Labels: enhancement

#59 [FEAT] : 회원이 모임에 가입되어 있는지 여부 확인 기능 구현
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassResponse.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
Labels: enhancement

#56 [FEAT] : 내 모임 일정 조회 기능 구현
  backend/src/main/java/z9/second/domain/user/controller/UserController.java
  backend/src/main/java/z9/second/domain/user/dto/UserResponse.java
  backend/src/main/java/z9/second/domain/user/service/UserService.java
  backend/src/main/java/z9/second/domain/user/service/UserServiceImpl.java
  backend/src/main/java/z9/second/global/config/SecurityConfig.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
  backend/src/main/java/z9/second/model/schedules/SchedulesCheckInEntityRepository.java
  backend/src/main/java/z9/second/model/schedules/SchedulesRepository.java
  backend/src/test/java/z9/second/domain/user/controller/UserControllerTest.java
  backend/src/test/java/z9/second/domain/user/service/UserServiceImplTest.java
  backend/src/test/java/z9/second/integration/SpringBootTestSupporter.java
  backend/src/test/java/z9/second/model/schedules/SchedulesRepositoryTest.java
Labels: enhancement

#65 [FEAT] : 강퇴된 회원 재가입 확인
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassResponse.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassBlackListRepository.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
Labels: enhancement

#81 [FEAT] : 로그인 회원 모임 조회 기능 구현
  backend/src/main/java/z9/second/domain/classes/repository/ClassRepository.java
  backend/src/main/java/z9/second/domain/user/controller/UserController.java
  backend/src/main/java/z9/second/domain/user/dto/UserResponse.java
  backend/src/main/java/z9/second/domain/user/service/UserService.java
  backend/src/main/java/z9/second/domain/user/service/UserServiceImpl.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
  backend/src/test/java/z9/second/domain/authentication/controller/AuthenticationControllerTest.java
  backend/src/test/java/z9/second/domain/authentication/service/AuthenticationServiceImplTest.java
  backend/src/test/java/z9/second/domain/classes/repository/ClassRepositoryTest.java
  backend/src/test/java/z9/second/domain/user/controller/UserControllerTest.java
  backend/src/test/java/z9/second/domain/user/service/UserServiceImplTest.java
  backend/src/test/java/z9/second/integration/SpringBootTestSupporter.java
  backend/src/test/java/z9/second/integration/factory/CheckInFactory.java
  backend/src/test/java/z9/second/integration/factory/ClassFactory.java
  backend/src/test/java/z9/second/integration/factory/FavoriteFactory.java
  backend/src/test/java/z9/second/integration/factory/SchedulesFactory.java
  backend/src/test/java/z9/second/integration/factory/UserFactory.java
  backend/src/test/java/z9/second/model/schedules/SchedulesRepositoryTest.java
  backend/src/test/java/z9/second/model/user/UserRepositoryTest.java
  backend/src/test/java/z9/second/model/userfavorite/UserFavoriteRepositoryTest.java
Labels: enhancement

#83 [TEST] : class 도메인 테스트 코드 작성 및 리팩토링
  backend/src/main/java/z9/second/domain/classes/controller/ClassController.java
  backend/src/main/java/z9/second/domain/classes/dto/ClassRequest.java
  backend/src/main/java/z9/second/domain/classes/entity/ClassEntity.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassBlackListRepository.java
  backend/src/main/java/z9/second/domain/classes/repository/ClassRepository.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/SuccessCode.java
  backend/src/test/java/z9/second/domain/classes/base/ClassBaseTest.java
  backend/src/test/java/z9/second/domain/classes/controller/ClassControllerTest.java
  backend/src/test/java/z9/second/domain/classes/dto/ClassRequestTest.java
  backend/src/test/java/z9/second/domain/classes/entity/ClassEntityTest.java
  backend/src/test/java/z9/second/domain/classes/service/ClassServiceTest.java
  backend/src/test/java/z9/second/integration/SpringBootTestSupporter.java
Labels: refactoring

#86 [FEAT] FE CLASS part 작업
  backend/src/main/java/z9/second/domain/classes/dto/ClassResponse.java
  backend/src/main/java/z9/second/domain/classes/service/ClassService.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  frontend/jsconfig.json
  frontend/public/index.html
  frontend/src/components/customList/CustomList.css
  frontend/src/components/customList/CustomList.jsx
  frontend/src/components/footer/Footer.jsx
  frontend/src/index.js
  frontend/src/pages/class/Class.jsx
  frontend/src/pages/class/[id]/Class.jsx
  frontend/src/pages/class/[id]/MemberList.jsx
  frontend/src/pages/home/Home.css
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/layout/Layout.css
  frontend/src/pages/layout/Layout.jsx
  frontend/src/pages/login/Login.jsx
  frontend/src/services/ClassService.jsx
Labels: enhancement, frontend

#91 [REFACTOR] : 인증/인가 시스템 테스트 추가 구성. (회원 탈퇴, 로그인)
  backend/src/main/java/z9/second/domain/authentication/service/AuthenticationServiceImpl.java
  backend/src/main/java/z9/second/global/response/ErrorCode.java
  backend/src/main/java/z9/second/global/security/provider/CustomAuthenticationProvider.java
  backend/src/main/java/z9/second/global/security/user/CustomUserDetails.java
  backend/src/test/java/z9/second/domain/authentication/controller/AuthenticationControllerTest.java
  backend/src/test/java/z9/second/domain/authentication/service/AuthenticationServiceImplTest.java
Labels: refactoring

#94 [FEAT] : API End-point 인가 권한 정리 진행
  backend/src/main/java/z9/second/global/config/SecurityConfig.java
Labels: enhancement
